-- ============================
-- Création des tables Snowflake
-- ============================

CREATE OR REPLACE TABLE DIM_TYPES_CONTRAT (
    TYPE_CONTRAT_ID VARCHAR PRIMARY KEY,
    LIBELLE_TYPE VARCHAR,
    DESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE DIM_BENEFICIAIRES (
    BENEFICIAIRE_ID VARCHAR PRIMARY KEY,
    NOM VARCHAR,
    PRENOM VARCHAR,
    DATE_NAISSANCE DATE,
    RELATION_ASSURE VARCHAR
);

CREATE OR REPLACE TABLE CONTRATS_ASSURANCE (
    CONTRAT_ID VARCHAR PRIMARY KEY,
    TYPE_CONTRAT_ID VARCHAR,
    BENEFICIAIRE_ID VARCHAR,
    DATE_SOUSCRIPTION DATE,
    DATE_ECHEANCE DATE,
    MONTANT_ASSURE NUMBER,
    STATUT VARCHAR,
    FOREIGN KEY (TYPE_CONTRAT_ID) REFERENCES DIM_TYPES_CONTRAT(TYPE_CONTRAT_ID),
    FOREIGN KEY (BENEFICIAIRE_ID) REFERENCES DIM_BENEFICIAIRES(BENEFICIAIRE_ID)
);
