-- ============================
-- 1. Création du stage interne
-- ============================

CREATE OR REPLACE STAGE ASSURANCE_STAGE;

-- ============================
-- 2. Chargement des fichiers CSV
-- ============================

COPY INTO DIM_TYPES_CONTRAT
FROM @ASSURANCE_STAGE/DIM_TYPES_CONTRAT.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

COPY INTO DIM_BENEFICIAIRES
FROM @ASSURANCE_STAGE/DIM_BENEFICIAIRES.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

COPY INTO CONTRATS_ASSURANCE
FROM @ASSURANCE_STAGE/CONTRATS_ASSURANCE.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);
