-- ============================
-- Vue : Contrats actifs
-- ============================

CREATE OR REPLACE VIEW V_CONTRATS_ACTIFS AS
SELECT 
    c.CONTRAT_ID,
    c.DATE_SOUSCRIPTION,
    c.DATE_ECHEANCE,
    c.MONTANT_ASSURE,
    c.STATUT,
    t.LIBELLE_TYPE,
    b.NOM,
    b.PRENOM
FROM CONTRATS_ASSURANCE c
LEFT JOIN DIM_TYPES_CONTRAT t ON c.TYPE_CONTRAT_ID = t.TYPE_CONTRAT_ID
LEFT JOIN DIM_BENEFICIAIRES b ON c.BENEFICIAIRE_ID = b.BENEFICIAIRE_ID
WHERE c.STATUT = 'Actif';

-- ============================
-- Vue : KPIs principaux
-- ============================

CREATE OR REPLACE VIEW V_KPI_ASSURANCE AS
SELECT
    COUNT(*) AS NB_CONTRATS,
    SUM(MONTANT_ASSURE) AS TOTAL_MONTANT_ASSURE,
    COUNT(DISTINCT BENEFICIAIRE_ID) AS NB_BENEFICIAIRES,
    COUNT_IF(STATUT = 'Résilié') AS NB_RESILIES
FROM CONTRATS_ASSURANCE;

-- ============================
-- Vue : Répartition par type
-- ============================

CREATE OR REPLACE VIEW V_REPARTITION_TYPES AS
SELECT
    t.LIBELLE_TYPE,
    COUNT(*) AS NB_CONTRATS,
    SUM(c.MONTANT_ASSURE) AS MONTANT_TOTAL
FROM CONTRATS_ASSURANCE c
LEFT JOIN DIM_TYPES_CONTRAT t ON c.TYPE_CONTRAT_ID = t.TYPE_CONTRAT_ID
GROUP BY t.LIBELLE_TYPE;
